"""Add active column to clients

Revision ID: 60646bf14c4e
Revises: afedd2251b75
Create Date: 2022-03-26 00:36:27.147927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60646bf14c4e'
down_revision = 'afedd2251b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'active')
    # ### end Alembic commands ###
